exports.pompes = require('../../assets/img/cover/pompes.png')
exports.bobinage = require('../../assets/img/cover/bobinage.jpg')
exports.vibrant = require('../../assets/img/cover/vibrant.jpg')
exports.moteurs_reducteurs = require('../../assets/img/cover/moteurs_reducteurs.jpg')
exports.tambours_moteurs = require('../../assets/img/cover/tambours_moteurs.jpg')
exports.variateur_mecanique = require('../../assets/img/cover/variateur_mecanique.jpg')